### PR TITLE
Completes The Room API

### PR DESCRIPTION
**Pull request by solomon-b**
I added functions to call all the Room endpoints https://spec.matrix.org/v1.1/client-server-api/#rooms-1

### CODE REVIEW

**Comment by solomon-b** [comment]
It would be nice to think through the module organization but I didn't want to do that in the same PR as adding a bunch of stuff.

**Comment by solomon-b** [comment]
Oh I just realized I should add lenses for the new data types. Don't merge til I do that.

**Review by TristanCacqueray — APPROVED** [review]
The additions look great, thanks!

**Comment by TristanCacqueray** [comment]
> It would be nice to think through the module organization but I didn't want to do that in the same PR as adding a bunch of stuff.

I don't have a preference. If you'd like to split the module, please go ahead :-)

**Comment by solomon-b** [comment]
There were actually only a few lenses to add. If were gonna do a module restructure, lets just do that in a separate PR.

**Pull request merged**
