### PR TITLE
Adds missing cabal version bounds.

### PR DESCRIPTION
**Pull request by solomon-b**
The missing cabal version bounds were causing the constraint solver to fail for me.

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
Arg, that's annoying. What was the error? I wish we could just avoid doing such busy work.

**Comment by solomon-b** [comment]
Cabal pulled in a newer version of base64 that actually wasn't compatible.

**Comment by TristanCacqueray** [comment]
I see, thanks. I created a new revision: https://hackage.haskell.org/package/matrix-client-0.1.5.0/revisions/

**Comment by solomon-b** [comment]
Thanks!

**Pull request merged**
